# Generated by Django 6.0.4 on 2026-04-25 06:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('location', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('description', models.TextField()),
                ('room_type', models.CharField(max_length=50)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('image1', models.ImageField(upload_to='rooms/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='rooms/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='rooms/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='rooms/')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
