# Generated by Django 6.0.4 on 2026-04-29 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='address',
            new_name='full_address',
        ),
    ]
