# Generated by Django 6.0.4 on 2026-04-29 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_address_room_full_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('Single Room', 'Single Room'), ('Double Room', 'Double Room'), ('2BHK', '2BHK'), ('3BHK', '3BHK'), ('PG', 'PG'), ('Flat', 'Flat')], max_length=50),
        ),
    ]
